'use client';

import React from 'react';
import { GlassCard } from '../ui/GlassCard';
import { Star, Quote, CheckCircle2, MessageSquare } from 'lucide-react';

export const TestimonialsSection: React.FC = () => {
  const testimonials = [
    {
      name: 'Rohan Sharma',
      company: 'Aura Luxury Skincare',
      location: 'Ahmedabad, India',
      image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      rating: 5,
      review: 'Growzzy completely transformed our Meta ad performance. We went from struggling to break even to a steady 7.8X ROAS. Jeel and his team in Ahmedabad are genuine growth partners who understand D2C metrics inside out.',
      stat: '7.8X ROAS Achieved',
    },
    {
      name: 'Karan Patel',
      company: 'Apex Real Estate Towers',
      location: 'Ahmedabad, India',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
      rating: 5,
      review: 'The quality of real estate buyer leads generated by Growzzy was unmatched. Their WhatsApp lead qualification campaign cut down junk calls by 90% and resulted in ₹14.5 Crore in property bookings!',
      stat: '1,840+ Verified Leads',
    },
    {
      name: 'Pooja Mehta',
      company: 'Vedic Organic Spices',
      location: 'Surat, India',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
      rating: 5,
      review: 'Their video reels and brand identity redesign made our organic reach explode by over 4.2M+ views. Growzzy is by far the best digital marketing agency we have worked with in Gujarat.',
      stat: '4.2M+ Reel Views',
    },
  ];

  return (
    <section id="testimonials" className="py-24 relative bg-[#F8FAFC] overflow-hidden">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full glass-pill border border-[#EF4444]/30 text-[#EF4444] text-xs font-bold tracking-widest uppercase mb-4">
            <MessageSquare className="w-4 h-4 text-[#EF4444]" /> CLIENT TESTIMONIALS
          </div>
          <h2 className="font-heading font-black text-4xl sm:text-6xl text-[#071B3B] leading-tight mb-4">
            What Our Clients Say <br />
            <span className="text-gradient">About Growzzy</span>
          </h2>
          <p className="font-sans text-base sm:text-lg text-gray-600">
            Real feedback from business owners and brand founders scaling with our agency.
          </p>
        </div>

        {/* 3 Testimonials Cards Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {testimonials.map((test, idx) => (
            <GlassCard
              key={idx}
              className="p-8 flex flex-col justify-between border border-gray-200/80 hover:border-[#EF4444]/50 shadow-md hover:shadow-2xl transition-all duration-300 relative group"
            >
              <Quote className="absolute top-6 right-6 w-12 h-12 text-[#071B3B]/10 pointer-events-none group-hover:text-[#EF4444]/20 transition-colors" />

              <div>
                {/* 5-Star Rating Header */}
                <div className="flex items-center gap-1 text-amber-400 mb-6">
                  {[...Array(test.rating)].map((_, i) => (
                    <Star key={i} className="w-5 h-5 fill-amber-400" />
                  ))}
                </div>

                {/* Review Text */}
                <p className="font-sans text-sm sm:text-base text-gray-700 italic leading-relaxed mb-8">
                  "{test.review}"
                </p>
              </div>

              {/* Client Info Footer */}
              <div className="pt-6 border-t border-gray-100 flex items-center gap-4">
                <div className="relative shrink-0">
                  <div className="w-14 h-14 rounded-full overflow-hidden border-2 border-white shadow-md">
                    <img src={test.image} alt={test.name} className="w-full h-full object-cover" />
                  </div>
                  <div className="absolute -bottom-1 -right-1 p-1 rounded-full bg-emerald-500 text-white">
                    <CheckCircle2 className="w-3 h-3" />
                  </div>
                </div>

                <div>
                  <h4 className="font-heading font-bold text-lg text-[#071B3B] group-hover:text-[#EF4444] transition-colors">
                    {test.name}
                  </h4>
                  <p className="text-xs text-gray-500 font-semibold">{test.company}</p>
                  <span className="inline-block mt-1 text-[10px] font-bold text-[#EF4444] uppercase tracking-wider">
                    {test.stat}
                  </span>
                </div>
              </div>
            </GlassCard>
          ))}
        </div>

      </div>
    </section>
  );
};
